name: Builds Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up 32-bit environment on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y g++-multilib cmake

    - name: Set up 32-bit environment on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install mingw --version=8.1.0 -y
        set PATH=C:\tools\mingw64\bin;%PATH%

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake for 32-bit
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          cmake -S . -B build -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then
          cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32
        fi

    - name: Build project
      run: cmake --build build


  # build:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Set up C++ compiler on Linux
  #     if: matrix.os == 'ubuntu-latest'
  #     run: sudo apt-get install -y g++ cmake

  #   - name: Set up C++ compiler on macOS
  #     if: matrix.os == 'macos-latest'
  #     run: brew install cmake

  #   - name: Set up C++ compiler on Windows
  #     if: matrix.os == 'windows-latest'
  #     run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

  #   - name: Create build directory
  #     run: mkdir build

  #   - name: Configure CMake
  #     run: cmake -S . -B build

  #   - name: Build project
  #     run: cmake --build build