name: Builds Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Create build directory
      run: mkdir build && cd build
      run: cmake ..
    
    - name: Builds the project
      run: cmake --build . --parallel


  # build:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Set up C++ compiler on Linux
  #     if: matrix.os == 'ubuntu-latest'
  #     run: sudo apt-get install -y g++ cmake

  #   - name: Set up C++ compiler on macOS
  #     if: matrix.os == 'macos-latest'
  #     run: brew install cmake

  #   - name: Set up C++ compiler on Windows
  #     if: matrix.os == 'windows-latest'
  #     run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

  #   - name: Create build directory
  #     run: mkdir build

  #   - name: Configure CMake
  #     run: cmake -S . -B build

  #   - name: Build project
  #     run: cmake --build build